const score=400;
console.log(score);
const newScore=new Number(100);
console.log(newScore);
console.log(newScore.toString().length);
console.log(newScore.toFixed(2));
const otherNumber =125.8920;
console.log(otherNumber.toPrecision(4));
const demoNumber=1000000;
console.log(demoNumber.toLocaleString());
